baseURL = "https://maxime-cls.github.io/argocd-tutorial/"
title = "ArgoCD Tutoriel"
theme = "hugo-theme-relearn"
languageCode = "fr-FR"
languageName = "Français"

[module]
  [[module.imports]]
    path = 'github.com/McShelby/hugo-theme-relearn'

[params]
themeVariant = ['relearn-light']
showVisitedLinks = true
disableSearch = false
disableLandingPageButton = true

[outputs]
home = ["HTML", "RSS",]
